// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// commataTest
Rcpp::DataFrame commataTest(const std::string contents, std::vector<std::size_t> col_select, std::size_t nrow);
RcppExport SEXP _commatatest_commataTest(SEXP contentsSEXP, SEXP col_selectSEXP, SEXP nrowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type contents(contentsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::size_t> >::type col_select(col_selectSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type nrow(nrowSEXP);
    rcpp_result_gen = Rcpp::wrap(commataTest(contents, col_select, nrow));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_commatatest_commataTest", (DL_FUNC) &_commatatest_commataTest, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_commatatest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
